site_name: Terraform Rockit Cloud Provider - User Guide
site_description: 'User documentation and reference for the
                   Terraform Rockit Cloud Provider'
use_directory_urls: false
copyright: Rockit Cloud
repo_name: C2Devel/terraform-provider-rockitcloud
repo_url: https://github.com/C2Devel/terraform-provider-rockitcloud
edit_uri: "https://github.com/C2Devel/terraform-provider-rockitcloud/tree/develop/website/docs"             
             
theme:
  name: material
  logo: images/favicon.ico
  favicon: images/favicon.ico
  palette:
    scheme: hashicorp
    primary: white
    accent: blue
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16

  features:
    - navigation.instant
    - content.tabs.link
    - content.code.copy

plugins:
  - search:
      lang:
        - en
  - awesome-pages

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - toc:
      permalink: "#"

extra_css:
     - 'assets/stylesheets/extra.css'
     - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
extra_javascript:
     - 'assets/stylesheets/extra.js'
