name: Run linters for the code

on:
  pull_request:
    branches: 'develop'
    paths: 'internal/**'
    types: [ labeled, unlabeled, opened, synchronize ]

jobs:
    code-linter:
        runs-on: ubuntu-22.04
        steps:
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21.x

        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}

        - name: Install tools
          run: make tools

        - name: Install Docker
          uses: crazy-max/ghaction-setup-docker@v3

        - name: Bump aws-sdk-go version if it's changed
          if: contains(github.event.pull_request.labels.*.name, 'NeedSDK')
          run: go mod tidy

        - name: Run linters for the code
          run: make lint
