name: Run unit tests for the code

on:
  pull_request:
    branches: 'develop'

jobs:
    unit-test:
        runs-on: ubuntu-22.04
        steps:
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21.x

        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}

        - name: Install tools
          run: make tools

        - name: Install Docker
          uses: crazy-max/ghaction-setup-docker@v3

        - name: Run unit tests for the code
          run: make test
