name: Publishing of the internal documentation

on: workflow_dispatch
    
jobs:
    Internal_doc_release:
        runs-on: ubuntu-22.04-large
        steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-python@v5 
          with:
            python-version: 'pypy3.10'

        - name: Install s3cmd
          run: sudo pip install s3cmd

        - name: Create S3 config
          run: echo "${{ secrets.s3_config }}" > ./.s3cfg

        - name: Run script
          run: ./scripts/build-docs.sh
