name: Release of the provider

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
    tests:
        runs-on: ubuntu
        steps:
        - uses: actions/checkout@v3

        - name: Import GPG key
          id: import_gpg
          uses: crazy-max/ghaction-import-gpg@v6
          with:
            gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
              version: '~> v2'
              args: release --clean --timeout 180m
            env:
              GITHUB_TOKEN: ${{ secrets.AUTOMATION_PAT }}
              GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
