name: Run tests

on:
    pull_request:
      types: [opened]
      branches: [develop]

jobs:
    tests:
        runs-on: ubuntu
        steps:
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21.x

        - uses: actions/checkout@v3

        - name: Run Unit tests
          run: |
            make test

        - name: Run acceptance tests
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_access_key }}
            EC2_URL: ${{ secrets.ec2_url }}
            PAAS_URL: ${{ secrets.paas_url }}
          run: |
            make testacc TESTS=TestAccPaaSServiceElasticSearch_basic PKG=ec2

    



